---
title: "Narrative mixed models"
output:
  pdf_document: default
  html_document: default
date: "2023-01-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load_session}
load("1213session")
```

```{r echo=FALSE}
library('readr')
library(MuMIn)
library(VWPre)
library(lme4)
library(optimx)
library(MuMIn)
library(lmerTest)
library(ggplot2)
all_data_continuous <- read_csv("./combined_with_percent_highlighted.csv")
normalize_col <- function(x){(x-min(x, na.rm = TRUE))/(max(x, na.rm = TRUE)-min(x, na.rm = TRUE))}
all_data_continuous$word_norm <- normalize_col(all_data_continuous$word)
all_data_continuous$norm_dt = all_data_continuous$IA_DWELL_TIME_SMOOTHED / all_data_continuous$word
all_data_continuous <- all_data_continuous %>%
    group_by(RECORDING_SESSION_LABEL) %>%
    mutate(across(c(norm_dt), scales::rescale))
all_data_continuous$norm_reg_path = all_data_continuous$IA_REGRESSION_PATH_DURATION_SMOOTHED / all_data_continuous$word
all_data_continuous$highlight = ifelse(all_data_continuous$category == 0, 0, 1)
all_data_continuous$valence_diff = all_data_continuous$valence_max_x - all_data_continuous$valence_min_x
all_data_continuous$arousal_diff = all_data_continuous$arousal_max_x - all_data_continuous$arousal_min_x
all_data_continuous$word_freq_avg <- normalize_col(all_data_continuous$word_freq / all_data_continuous$word)
all_data_continuous$word_freq_norm <- normalize_col(all_data_continuous$word_freq)
engagement_highlights <- read_csv("./engagement_highlights.csv")
engagement_highlights$percentage_highlighted <- engagement_highlights$highlight_weight / engagement_highlights$word
# rename column 'Unnamed:\ 0' to 'sentence'
all_data_continuous <- all_data_continuous %>%
    rename('sentence' = 'Unnamed:\ 0')

all_data_continuous <- all_data_continuous %>%
   rename('text' = '0')
all_data_continuous$no_highlight <- ifelse(all_data_continuous$category == 0, 1, 0)
all_data_continuous$present <- ifelse(all_data_continuous$category == 1, 1, 0)
all_data_continuous$confused <- ifelse(all_data_continuous$category == 2, 1, 0)
all_data_continuous$curious <- ifelse(all_data_continuous$category == 3, 1, 0)
all_data_continuous$connected <- ifelse(all_data_continuous$category == 4, 1, 0)
all_data_continuous$other <- ifelse(all_data_continuous$category == 5, 1, 0)

sm_sentiment <- read_tsv('../emotional_story_arcs/data/kelsey/results/schoolmistress.sentiment_window5',
                                     col_names = c("negative_smoothed", "neutral_smoothed", "positive_smoothed"))
el_sentiment <- read_tsv('../emotional_story_arcs/data/kelsey/results/expensivelessons.sentiment_window5',
                         col_names = c("negative_smoothed", "neutral_smoothed", "positive_smoothed"))

sm_valence <- read_tsv('../emotional_story_arcs/data/kelsey/results/schoolmistress.valence',
                                     col_names = c("valence_diff_smoothed", "arousal_diff_smoothed"))
el_valence <- read_tsv('../emotional_story_arcs/data/kelsey/results/expensivelessons.valence',
                         col_names = c("valence_diff_smoothed", "arousal_diff_smoothed"))

el_story <- all_data_continuous[all_data_continuous$story == 'EL',]
sm_story <- all_data_continuous[all_data_continuous$story == 'SM',]
el_sentiment$sentence <- 1:nrow(el_sentiment) - 1
sm_sentiment$sentence <- 1:nrow(sm_sentiment) - 1
el_valence$sentence <- 1:nrow(el_valence) - 1
sm_valence$sentence <- 1:nrow(sm_valence) - 1
el_with_sent = merge(x = el_story, y = el_sentiment, by = "sentence")
sm_with_sent = merge(x = sm_story, y = sm_sentiment, by = "sentence")

el_all_smoothed = merge(x = el_with_sent, y = el_valence, by = "sentence")
sm_all_smoothed = merge(x = sm_with_sent, y = sm_valence, by = "sentence")
el_all_smoothed <- el_all_smoothed %>%
    group_by(story, sentence) %>%
    summarise(sum_proportion_x = sum(proportion_x), negative= mean(negative_smoothed), positive = mean(positive_smoothed), neutral = mean(neutral_smoothed), valence_diff = mean(valence_diff_smoothed), arousal_diff = mean(arousal_diff_smoothed), avg_dt = sum(norm_dt), no_highlight = sum(no_highlight), present = sum(present), confused = sum(confused), curious = sum(curious), connected = sum(connected), other = sum(other), text=first(text))%>%
    mutate(across(c(sum_proportion_x), scales::rescale))%>%
    mutate(across(c(avg_dt), scales::rescale))%>%
    mutate(across(c(present), scales::rescale))%>%
    mutate(across(c(confused), scales::rescale))%>%
    mutate(across(c(curious), scales::rescale))%>%
    mutate(across(c(connected), scales::rescale))%>%
    mutate(across(c(other), scales::rescale))

sm_all_smoothed <- sm_all_smoothed %>%
    group_by(story, sentence) %>%
    summarise(sum_proportion_x = sum(proportion_x), negative= mean(negative_smoothed), positive = mean(positive_smoothed), neutral = mean(neutral_smoothed), valence_diff = mean(valence_diff_smoothed), arousal_diff = mean(arousal_diff_smoothed), avg_dt = sum(norm_dt), no_highlight = sum(no_highlight), present = sum(present), confused = sum(confused), curious = sum(curious), connected = sum(connected), other = sum(other), text=first(text))%>%
    mutate(across(c(sum_proportion_x), scales::rescale))%>%
    mutate(across(c(avg_dt), scales::rescale))%>%
    mutate(across(c(present), scales::rescale))%>%
    mutate(across(c(confused), scales::rescale))%>%
    mutate(across(c(curious), scales::rescale))%>%
    mutate(across(c(connected), scales::rescale))%>%
    mutate(across(c(other), scales::rescale))
```
```{r}
all_data_continuous <- all_data_continuous %>%
    group_by(RECORDING_SESSION_LABEL)
```

```{r}
model_highlight_proportion = lmer(proportion_x ~ 1 + word_norm + word_freq_norm + positive + negative + concreteness + valence_avg_x + norm_dt + arousal_avg_x + valence_diff + arousal_diff + (1 | RECORDING_SESSION_LABEL) + (1 | story), data=all_data_continuous)
model_dwell_time = lmer(norm_dt ~ 1   + word_norm + word_freq_norm  + negative + concreteness + valence_avg_x + arousal_avg_x +valence_diff  + arousal_diff + proportion_x + (1 | RECORDING_SESSION_LABEL) + (1 | story), data=all_data_continuous)
```

## Predict continuous highlight annotation

i.e. what proportion of the sentence is highlighted

```{r}
summary(model_highlight_proportion)
print('variance explained by fixed variables and by both fixed and random variables')
r.squaredGLMM(model_highlight_proportion)
coef(model_highlight_proportion)
```
## Predict dwell time
```{r}
summary(model_dwell_time, correlation=FALSE)
print('variance explained by fixed variables and by both fixed and random variables')
r.squaredGLMM(model_dwell_time)
coef(model_dwell_time)
```



```{r}
library(ggplot2)
ggplot(all_data_continuous ,aes(x=arousal_diff, y=proportion_x, color=story)) + geom_point(alpha = .5) + facet_wrap(~RECORDING_SESSION_LABEL, nrow = 4, ncol = 6)
engagement_highlights_el <- engagement_highlights[engagement_highlights$story == 'EL',]
engagement_highlights_sm <- engagement_highlights[engagement_highlights$story == 'SM',]
ggplot(all_data_continuous ,aes(x=valence_diff, y=norm_dt, color=story))+ geom_point(alpha = .5)   + facet_wrap(~RECORDING_SESSION_LABEL, nrow = 4, ncol = 6)
ggplot(all_data_continuous ,aes(x=norm_dt, y=proportion_x, color=story))+ geom_point(alpha = .5)   + facet_wrap(~RECORDING_SESSION_LABEL, nrow = 4, ncol = 6)
ggplot(engagement_highlights_el, aes(x=engagement_score, y=percentage_highlighted, color=story)) + geom_point() +
  geom_smooth(method=lm,  linetype="dashed",
             color="darkred", fill="blue")
ggplot(engagement_highlights_sm, aes(x=engagement_score, y=percentage_highlighted, color=story)) + geom_point() +
  geom_smooth(method=lm,  linetype="dashed",
             color="darkred", fill="blue")
ggplot(engagement_highlights, aes(x=engagement_score, y=percentage_highlighted, color=story)) + geom_point() +
  geom_smooth(method=lm,  linetype="dashed",
             color="darkred", fill="blue")

```

```{r}
#filtered_df <- subset(all_data_continuous, all_data_continuous$category > 0)
boxplot(norm_dt ~ RECORDING_SESSION_LABEL,
col=c("white","lightgray"), all_data_continuous)
```
```{r}
options(repr.plot.width=1000, repr.plot.height=400)
```
```{r}
# graph of combined highlight proportion count per sentence where sentence is the x axis and the sum of proportion_x is the y axis


combined_stories <- all_data_continuous %>%
    group_by(sentence) %>%
    summarise(sum_proportion_x = sum(proportion_x), negative= mean(negative), positive = mean(positive), valence_diff = mean(valence_diff), arousal_diff = mean(arousal_diff), avg_dt = mean(norm_dt))%>%
    mutate(across(c(sum_proportion_x), scales::rescale))%>%
    mutate(across(c(avg_dt), scales::rescale))

```
histogram with sentence as x axis and sum of proportion_x as y axis with 40 bins with 'negative'  line overlaying it
```{r}
highlights_features_plot <- ggplot(el_all_smoothed, aes(x=sentence, y=sum_proportion_x)) + 
  geom_bar(aes(fill = "Sum of highlights"), stat="identity", alpha=0.5, show.legend=TRUE) + 
  labs(x='Sentence', y='Scaled sum of reader highlights', title='Sentiment and highlights for Expensive Lessons') +
  geom_line(aes(x=sentence, y=negative, color = "Negative"), alpha=0.5, linewidth=0.5, show.legend =TRUE) +
  geom_line(aes(x=sentence, y=positive, color = "Positive"), alpha=0.7, linewidth=0.5, show.legend =TRUE) +
  scale_color_manual(values=c("Negative"= "red", "Positive"="forestgreen"), name="Sentiment") +
  scale_fill_manual(values = "steelblue", name = "Reader Highlights") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5),
        plot.background = element_rect(size = 4, color = "black", fill = "white"))
ggsave("el_highlights_sentiment.png", plot = highlights_features_plot, width = 10, height = 8, dpi = 300)

highlights_features_plot <- ggplot(el_all_smoothed, aes(x=sentence, y=sum_proportion_x)) + 
  geom_bar(aes(fill = "Sum of highlights"), stat="identity", alpha=0.5, show.legend=TRUE) + 
  labs(x='Sentence', y='Scaled sum of reader highlights', title='Arousal and Valence difference and highlights for Expensive Lessons') +
  geom_line(aes(x=sentence, y=arousal_diff, color = "Arousal Difference"), alpha=0.5, linewidth=0.5, show.legend =TRUE) +
  geom_line(aes(x=sentence, y=valence_diff, color = "Valence Difference"), alpha=0.7, linewidth=0.5, show.legend =TRUE) +
  scale_color_manual(values=c("Arousal Difference"= "tomato", "Valence Difference"="purple"), name="Text feature") +
  scale_fill_manual(values = "steelblue", name = "Reader Highlights") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5),
        plot.background = element_rect(size = 4, color = "black", fill = "white"),
        plot.margin = margin(2, 2, 2, 2, "cm"),)
ggsave("el_highlights_val_arousal.png", plot = highlights_features_plot, width = 10, height = 8, dpi = 300)

highlights_features_plot <- ggplot(el_all_smoothed, aes(x=sentence, y=sum_proportion_x)) + 
  geom_bar(aes(fill = "Sum of highlights"), stat="identity", alpha=0.5, show.legend=TRUE) + 
  labs(x='Sentence', y='Scaled sum of reader highlights', title='Average scaled dwell time and highlights for Expensive Lessons') +
  geom_line(aes(x=sentence, y=avg_dt, color = "Average dwell time"), alpha=0.5, linewidth=0.5, show.legend =TRUE) +
  scale_color_manual(values=c("Average dwell time"="purple"), name = "Eye tracking measurement") +
  scale_fill_manual(values = "steelblue", name = "Reader Highlights") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5),
        plot.background = element_rect(size = 4, color = "black", fill = "white"),
        plot.margin = margin(2, 2, 2, 2, "cm"),)
ggsave("el_highlights_dt.png", plot = highlights_features_plot, width = 10, height = 8, dpi = 300)


# create a bar plot with sentence as the x axis and these variables stacked on top of each other: no_highlight, present, confused, curious, connected, other
```
```{r}
library(plotly)
p <- plot_ly(data=el_story, x = ~sentence, y = ~present, type = 'bar', name = 'present', hovertemplate=~paste(gsub('(.{1,45})(\\s|$)', '\\1\n', text), "Count:", present)) %>%
    add_trace(y = ~confused, name = 'confused', hovertemplate=~paste(gsub('(.{1,45})(\\s|$)', '\\1\n', text), "Count:", confused)) %>%
    add_trace(y = ~curious, name = 'curious', hovertemplate=~paste(gsub('(.{1,45})(\\s|$)', '\\1\n', text), "Count:", curious)) %>%
    add_trace(y = ~connected, name = 'connected', hovertemplate=~paste(gsub('(.{1,45})(\\s|$)', '\\1\n', text), "Count:", connected)) %>%
    add_trace(y = ~other, name = 'other', hovertemplate=~paste(gsub('(.{1,45})(\\s|$)', '\\1\n', text), "Count:", other)) %>%
    layout( barmode = 'stack',
    hoverlabel = list(
    font = list(
      family = "Sitka Small",
      size = 16,
      color = "white"),
    widths = lcm(1))) %>% add_markers()

htmlwidgets::saveWidget(p, "highlights_el.html")

```

```{r}
p <- plot_ly(data=el_story, x = ~sentence, y = ~present,  type = 'bar', name = 'present', hovertemplate=~paste(gsub('(.{1,45})(\\s|$)', '\\1\n', text), "Count:", present)) %>%
    add_trace(y = ~confused, name = 'confused', hovertemplate=~paste(gsub('(.{1,45})(\\s|$)', '\\1\n', text), "Count:", confused)) %>%
    add_trace(y = ~curious, name = 'curious', hovertemplate=~paste(gsub('(.{1,45})(\\s|$)', '\\1\n', text), "Count:", curious)) %>%
    add_trace(y = ~connected, name = 'connected', hovertemplate=~paste(gsub('(.{1,45})(\\s|$)', '\\1\n', text), "Count:", connected)) %>%
    add_trace(y = ~other, name = 'other', hovertemplate=~paste(gsub('(.{1,45})(\\s|$)', '\\1\n', text), "Count:", other)) %>%  
    add_trace(y = ~negative, name = 'negative sentiment', type = 'scatter', mode = 'lines', hovertemplate=~paste(gsub('(.{1,45})(\\s|$)', '\\1\n', text), "Count:", other)) %>%

    layout(
      barmode = 'stack',
    hoverlabel = list(
    font = list(
      family = "Sitka Small",
      size = 16,
      color = "white"),
    widths = lcm(1))) %>% add_markers()

htmlwidgets::saveWidget(p, "highlights_el.html")
```


```{r}
highlights_features_plot <- ggplot(sm_all_smoothed, aes(x=sentence, y=sum_proportion_x)) + 
  geom_bar(aes(fill = "Sum of highlights"), stat="identity", alpha=0.5, show.legend=TRUE) + 
  labs(x='Sentence', y='Scaled sum of reader highlights', title='Sentiment and highlights for Schoolmistress') +
  geom_line(aes(x=sentence, y=negative, color = "Negative"), alpha=0.5, linewidth=0.5, show.legend =TRUE) +
  geom_line(aes(x=sentence, y=positive, color = "Positive"), alpha=0.7, linewidth=0.5, show.legend =TRUE) +
  scale_color_manual(values=c("Negative"= "red", "Positive"="forestgreen"), name="Sentiment") +
  scale_fill_manual(values = "steelblue", name = "Reader Highlights") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5),
        plot.background = element_rect(size = 4, color = "black", fill = "white"))
ggsave("sm_highlights_sentiment.png", plot = highlights_features_plot, width = 10, height = 8, dpi = 300)

highlights_features_plot <- ggplot(sm_all_smoothed, aes(x=sentence, y=sum_proportion_x)) + 
  geom_bar(aes(fill = "Sum of highlights"), stat="identity", alpha=0.5, show.legend=TRUE) + 
  labs(x='Sentence', y='Scaled sum of reader highlights', title='Arousal and Valence difference and highlights for Schoolmistress') +
  geom_line(aes(x=sentence, y=arousal_diff, color = "Arousal Difference"), alpha=0.5, linewidth=0.5, show.legend =TRUE) +
  geom_line(aes(x=sentence, y=valence_diff, color = "Valence Difference"), alpha=0.7, linewidth=0.5, show.legend =TRUE) +
  scale_color_manual(values=c("Arousal Difference"= "tomato", "Valence Difference"="purple"), name="Text feature") +
  scale_fill_manual(values = "steelblue", name = "Reader Highlights") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5),
        plot.background = element_rect(size = 4, color = "black", fill = "white"),
        plot.margin = margin(2, 2, 2, 2, "cm"),)
ggsave("sm_highlights_val_arousal.png", plot = highlights_features_plot, width = 10, height = 8, dpi = 300)

highlights_features_plot <- ggplot(sm_all_smoothed, aes(x=sentence, y=sum_proportion_x)) + 
  geom_bar(aes(fill = "Sum of highlights"), stat="identity", alpha=0.5, show.legend=TRUE) + 
  labs(x='Sentence', y='Scaled sum of reader highlights', title='Average scaled dwell time and highlights for Schoolmistress') +
  geom_line(aes(x=sentence, y=avg_dt, color = "Average dwell time"), alpha=0.5, linewidth=0.5, show.legend =TRUE) +
  scale_color_manual(values=c("Average dwell time"="purple"), name = "Eye tracking measurement") +
  scale_fill_manual(values = "steelblue", name = "Reader Highlights") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5),
        plot.background = element_rect(size = 4, color = "black", fill = "white"),
        plot.margin = margin(2, 2, 2, 2, "cm"),)
ggsave("sm_highlights_dt.png", plot = highlights_features_plot, width = 10, height = 8, dpi = 300)
```


```{r}
highlights_features_plot <- ggplot(combined_stories, aes(x=sentence, y=sum_proportion_x)) + 
  geom_bar(aes(fill = "Sum of highlights"), stat="identity", alpha=0.5, show.legend=TRUE) + 
  labs(x='Sentence', y='Scaled sum of reader highlights', title='Sentiment and highlights for Both') +
  geom_line(aes(x=sentence, y=negative, color = "Negative"), alpha=0.5, linewidth=0.5, show.legend =TRUE) +
  geom_line(aes(x=sentence, y=positive, color = "Positive"), alpha=0.7, linewidth=0.5, show.legend =TRUE) +
  scale_color_manual(values=c("Negative"= "red", "Positive"="forestgreen"), name="Sentiment") +
  scale_fill_manual(values = "steelblue", name = "Reader Highlights") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5),
        plot.background = element_rect(size = 4, color = "black", fill = "white"))
ggsave("both_highlights_sentiment.png", plot = highlights_features_plot, width = 10, height = 8, dpi = 300)

highlights_features_plot <- ggplot(sm_story, aes(x=sentence, y=sum_proportion_x)) + 
  geom_bar(aes(fill = "Sum of highlights"), stat="identity", alpha=0.5, show.legend=TRUE) + 
  labs(x='Sentence', y='Scaled sum of reader highlights', title='Arousal and Valence difference and highlights for Both') +
  geom_line(aes(x=sentence, y=arousal_diff, color = "Arousal Difference"), alpha=0.5, linewidth=0.5, show.legend =TRUE) +
  geom_line(aes(x=sentence, y=valence_diff, color = "Valence Difference"), alpha=0.7, linewidth=0.5, show.legend =TRUE) +
  scale_color_manual(values=c("Arousal Difference"= "tomato", "Valence Difference"="purple"), name="Text feature") +
  scale_fill_manual(values = "steelblue", name = "Reader Highlights") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5),
        plot.background = element_rect(size = 4, color = "black", fill = "white"),
        plot.margin = margin(2, 2, 2, 2, "cm"),)
ggsave("both_highlights_val_arousal.png", plot = highlights_features_plot, width = 10, height = 8, dpi = 300)

highlights_features_plot <- ggplot(sm_story, aes(x=sentence, y=sum_proportion_x)) + 
  geom_bar(aes(fill = "Sum of highlights"), stat="identity", alpha=0.5, show.legend=TRUE) + 
  labs(x='Sentence', y='Scaled sum of reader highlights', title='Average scaled dwell time and highlights for Both') +
  geom_line(aes(x=sentence, y=avg_dt, color = "Average dwell time"), alpha=0.5, linewidth=0.5, show.legend =TRUE) +
  scale_color_manual(values=c("Average dwell time"="purple"), name = "Eye tracking measurement") +
  scale_fill_manual(values = "steelblue", name = "Reader Highlights") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5),
        plot.background = element_rect(size = 4, color = "black", fill = "white"),
        plot.margin = margin(2, 2, 2, 2, "cm"),)
ggsave("both_highlights_dt.png", plot = highlights_features_plot, width = 10, height = 8, dpi = 300)
```


```{r}
write.csv(all_data_continuous, file='./all_data_continuous')
```
